# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption', '0002_auto_20160803_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
