# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption', '0003_auto_20160804_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
